name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install latest mdbook
      run: |
        tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
        url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
        mkdir mdbook
        curl -sSL $url | tar -xz --directory=./mdbook
        echo `pwd`/mdbook >> $GITHUB_PATH
    - name: Build HTML
      run: |
        mdbook build
    - name: Deploy HTML
      shell: bash
      env:
        DEPLOY_KEY: ${{ secrets.deploy_key }}
        KNOWN_HOSTS: ${{ secrets.known_hosts }}
      run: |
        eval $(ssh-agent -s)
        ssh-add - <<<${DEPLOY_KEY}
        mkdir ${HOME}/.ssh
        echo "${KNOWN_HOSTS}" >> ${HOME}/.ssh/known_hosts
        ssh-keygen -Hf ${HOME}/.ssh/known_hosts
        time rsync -rltF --include=/.well-known book/* deploy-interrail@skellig.partim.org: --delete-after
